### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by ghost** [vhoen/Android-Mobotix-MJPEG-Client#1]
is it possible to play more then one video simultaneously in android list view ?

**Comment by vhoen** [comment]
As of now it is not possible. It might be with some modification but I've never tried it. If you were to try I would be interested to hear back from you.

**Comment by ghost** [comment]
i worked with Android VLC SDK to play multiple stream. I have 4 seconds delay. is it possible to fix with android vlc sdk ?

**Comment by vhoen** [comment]
Frankly, no idea, and I don't have any mobotix device to test with.
